### ISSUE TITLE
Doesn't have any preferences button

### ISSUE THREAD

**Issue by benintech** [andia89/order-icons#10]
Debian 11 / Gnome 3.38 :

![order-gnome-shell_no-prefs](https://user-images.githubusercontent.com/5140169/188319206-2983b04a-d6fe-4167-97f9-f3d3e825a85e.png)

**Comment by andia89** [comment]
Gnome version is too old. Preferences only exist for gnome 40 and later. You can try the old way though but I'm not 100% sure that still works https://github.com/andia89/order-icons/blob/6f05a1734cde6dcf29db5735dbcb29ccce68c3e9/README.md

**Comment by benintech** [comment]
OK thanks ! I'll try it again on G42, I am planning to install it anyway.
