### ISSUE TITLE
Feature request: Re-add indicators on panel

### ISSUE THREAD

**Issue by Zatan16** [andia89/order-icons#18]
Add a way to add back the indicators that were removed previously. For example, by mistake I had removed the App Name indicator, now it has moved completely to the front and is not visible on the list, and hence can't be moved. Re-adding the indicator would be helpful. Also, disabling could be added so that the indicator doesn't show up in the panel but is still there in the list (and is greyed out) and can be enabled any time we want. This would allow us to delete the indicators without losing the order they were previously present.

**Comment by andia89** [comment]
I think I won't implement this. reason is that I don't think it is necessary. If you by mistake click the delete button, just close the settings window and open it again, then the icon should be there again. Removing icons from the list is just to remove clutter when there are so many icons from old apps that are not used anymore
