### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by sol2070** [andia89/order-icons#19]
This extension is very useful. Thanks for it! Any idea when Gnome 46 will be supported?

**Comment by InklingGirl** [comment]
Bump, as the latest LTS version of Ubuntu is launching w/ GNOME 46 this month, so it would be great to have this extension up-to-date on https://extensions.gnome.org/extension/2114! Thanks.

**Comment by andia89** [comment]
I'll add support on the weekend

**Comment by InklingGirl** [comment]
Thank you!

**Comment by InklingGirl** [comment]
There is a [PR for this](https://github.com/andia89/order-icons/pull/20) in the chamber.

**Comment by InklingGirl** [comment]
Ubuntu 24.04 LTS w/ GNOME 46 has launched today.
