### ISSUE TITLE
Push extension to extensions.gnome.org

### ISSUE THREAD

**Issue by BjoernDaase** [andia89/order-icons#3]
Would you mind pushing this extension to extensions.gnome.org to give users an easier installation process and get a wider range of people to be able to use this extension?

**Comment by andia89** [comment]
Yep. It's under review for quite some time now. Hope it's sorted out soon

**Comment by andia89** [comment]
https://extensions.gnome.org/extension/2114/order-gnome-shell-extensions/

**Comment by BjoernDaase** [comment]
Perfect, thanks.

Just two things:  
1. Why is the name of the extension: "Order gnome-shell extensions" and not something like "Order gnome-shell appindicator icons"?
2. Could you please add 3.34 to the supported versions (people stumble over that and think, their gnome-shell version might not be supported)?
