### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by diego-pvlk** [andia89/order-icons#6]
Fantastic extension, thank you.

The icons don't show up with default Adwaita icons, Fedora 36:
![missing icons](https://user-images.githubusercontent.com/25941156/165093102-dacef46b-7cf0-4207-9d31-26937cc2eca4.png)

Maybe use these ones instead?
```
go-up-symbolic
go-down-symbolic
edit-delete-symbolic
```

**Comment by andia89** [comment]
Fixed. Thanks
